### ISSUE TITLE
Community Edition: HTTP Error 500.0 - Internal Server Error

### ISSUE THREAD

**Issue by kottimon** [glueckkanja/gk-scepman#8]
Hi!

I've setup a marketplace installation of SCEPMan CE. Installation and configuration goes without issues and SCEPMan dashboard looks ok:
![image](https://user-images.githubusercontent.com/17312355/103277151-a7a7a200-49c8-11eb-8e11-685ef0f60c5d.png)

But going to /certsrv/mscep/mscep.dll immediately generates http 500 errors, as does certificate requests from devices.

From logstream we get this:
HTTP Error 500.0 - Internal Server Error
The page cannot be displayed because an internal server error has occurred.
IIS received the request; however, an internal error occurred during the processing of the request. The root cause of this error depends on which module handles the request and what was happening in the worker process when this error occurred
IIS was not able to access the web.config file for the Web site or application. This can occur if the NTFS permissions are set incorrectly.
IIS was not able to process configuration for the Web site or application.
The authenticated user does not have permission to use this DLL.
The request is mapped to a managed handler but the .NET Extensibility Feature is not installed.
Things you can try:Ensure that the NTFS permissions for the web.config file are correct and allow access to the Web server's machine account

Looking inside debug console I cannot find the /certsrv/ directory in the site, but I don't know if that is by design:
cd "D:\home\site\wwwroot\certsrv\mscep"
cd : Cannot find path 'D:\home\site\wwwroot\certsrv\mscep' because it does not exist.'

This however does work:
https://scepman-apppqcrk5pytorzm.azurewebsites.net/certsrv/mscep/mscep.dll/pkiclient.exe?operation=GetCACaps

Kind regards,
Jakob

**Comment by okieselbach** [comment]
Hey @kottimon, 

the certsrv/mscep/mscep.dll is a virtual path it is not intended to be called by a browser get. In a future version 1.7 we will display you a meaningful webpage. Until know the 500 is expected there if called by a browser. So the rest if looking good. How are your certificate settings? And what are your device names in AAD?. if the subject alternative name (SAN) does not have the correct device name or user name (depending if you deploy user or device certs) it will not be found in AAD. So check your certificate if the SAN entry is correct and the entry is an actual resource in AAD. Otherwise you will not receive a certificate.

best,
Oliver

**Comment by kottimon** [comment]
Hey!

Yeah I kinda figured after the GetCACaps operation worked.. :) 
Good to know that the 
/certsrv/mscep/mscep.dll is supposed to generate a 500 and not a 403 as in windows scep deployments!

Changed the scep-profile in Intune in accordance with your suggestion, and low and behold, certificates are flowing..

Thank you very much for a swift response!
Have a good new year!

regards,
Jakob
